#!/bin/bash

## Сохраняем все переменные окружения в массив
#env_vars=($(env | grep -v "^HOME="))
#
## Формируем строку для передачи в sudo
#env_string=""
#for var in "${env_vars[@]}"; do
#  env_string+=" $var"
#done

#RES: SHELL,SESSION_MANAGER,QT_ACCESSIBILITY,QT_SCREEN_SCALE_FACTORS,XDG_CONFIG_DIRS,XDG_SESSION_PATH,NVM_INC,TERMINAL_EMULATOR,LANGUAGE,SSH_AUTH_SOCK,JETBRAINSCLIENT_VM_OPTIONS,GOLAND_VM_OPTIONS,TERM_SESSION_ID,WEBSTORM_VM_OPTIONS,PHPSTORM_VM_OPTIONS,DESKTOP_SESSION,SSH_AGENT_PID,GTK_RC_FILES,XCURSOR_SIZE,GTK_MODULES,XDG_SEAT,PWD,WEBIDE_VM_OPTIONS,GATEWAY_VM_OPTIONS,LOGNAME,XDG_SESSION_DESKTOP,XDG_SESSION_TYPE,DATASPELL_VM_OPTIONS,GPG_AGENT_INFO,SYSTEMD_EXEC_PID,XAUTHORITY,DESKTOP_STARTUP_ID,XDG_GREETER_DATA_DIR,GTK2_RC_FILES,HOME,IM_CONFIG_PHASE,LANG,LS_COLORS,XDG_CURRENT_DESKTOP,RUSTROVER_VM_OPTIONS,_INTELLIJ_FORCE_PREPEND_PATH,XDG_SEAT_PATH,INVOCATION_ID,QTWEBENGINE_DICTIONARIES_PATH,MANAGERPID,KDE_SESSION_UID,NVM_DIR,XDG_SESSION_CLASS,TERM,USER,IDEA_VM_OPTIONS,KDE_SESSION_VERSION,DISPLAY,SHLVL,NVM_CD_FLAGS,STUDIO_VM_OPTIONS,XDG_VTNR,XDG_SESSION_ID,CLION_VM_OPTIONS,DATAGRIP_VM_OPTIONS,RIDER_VM_OPTIONS,JETBRAINS_CLIENT_VM_OPTIONS,XDG_RUNTIME_DIR,PYCHARM_VM_OPTIONS,QT_AUTO_SCREEN_SCALE_FACTOR,JOURNAL_STREAM,XCURSOR_THEME,GTK3_MODULES,XDG_DATA_DIRS,KDE_FULL_SESSION,PATH,GDMSESSION,DBUS_SESSION_BUS_ADDRESS,KDE_APPLICATIONS_AS_SCOPE,NVM_BIN,AQUA_VM_OPTIONS,RUBYMINE_VM_OPTIONS,DEVECOSTUDIO_VM_OPTIONS,_


env_string=""
#envs_exclude=""
envs_exclude=",HOME"
envs_exclude=",HOME,SHELL,SESSION_MANAGER"
for var in $(env | cut -d'=' -f1); do
  if echo "${envs_exclude}" | grep -q ",$var,\|,$var$"; then
    echo "#SKIP: Переменная $var найдена в строке"
    continue;
  else
    echo "#ADD: Переменная $var не найдена в строке"
  fi
  env_string+="$var,"
done
echo "#RES: ${env_string%,}"

#env | cut -d'=' -f1 | tr '\n' ',' | sed 's/,$//'

